import '/public/styles/styles.css'

export const metadata = {
  title: 'Pedidos Bar',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          <meta name="viewport" content="width=device-width, user-scalable=no"></meta>
        </head>
        <body>{children}</body>
      </html>
    </>
  )
}
